#!/usr/bin/env ruby
# Note: the shebang above expects ruby to be intalled through rbenv
#
# Executable wrapper for starting an RSMP site
# Expect settings files to be present

require_relative 'site'
require 'optparse'

dir = File.dirname(__FILE__)
options = {
	site_settings_path: File.expand_path(File.join(dir,'config/site.yaml')),
	site_settings: {
	}
}

options_parser = OptionParser.new do |opts|
  opts.banner = "Usage: site [options]"
  opts.on('-s IP:PORT', '--supervisors IP:PORT', 'Connect supervisor(s) at IP:PORT,...') do |list|
  	list = list.split ','
  	list.each do |supervisor|
			ip, port = supervisor.split ':'
			ip = '127.0.0.1' if ip.empty?
			port = '12111' if port.empty?
	    options[:site_settings][:supervisors] = [] unless options[:site_settings][:supervisors]
			options[:site_settings][:supervisors] << {"ip"=>ip, "port"=>port}
		end
  end
  opts.on('-i ID', '--site-id ID', 'Use site id ID') do |id|
    options[:site_settings][:site_id] = id
  end
  opts.on( '-h', '--help', 'Show help' ) do
    puts opts
    exit
  end
end

begin
	options_parser.parse!
rescue OptionParser::ParseError => e
    puts e
    puts options_parser
    exit 1
end

site = RSMP::Site.new options
site.start
