#!/usr/bin/env ruby
# Note: the shebang above expects ruby to be intalled through rbenv
#
# Executable wrapper for starting an RSMP supervisor (server)
# Expect a settings files to be present at config/supervisor.yaml

require_relative 'supervisor'

dir = File.dirname(__FILE__)
supervisor_settings_path = File.expand_path File.join(dir,'config/supervisor.yaml')
sites_settings_path = File.expand_path File.join(dir,'config/sites.yaml')
server = RSMP::Supervisor.new supervisor_settings_path: supervisor_settings_path, 
															sites_settings_path: sites_settings_path
server.run
