#!/usr/bin/env ruby
#note: the shebang above expects ruby to be intalled through rbenv

# executable wrapper for starting an rsmp supervisor (server)
#
# expect settings files to be present

require_relative 'supervisor'

# settings paths
dir = File.dirname(__FILE__)
supervisor_settings_path = File.expand_path File.join(dir,'config/supervisor.yaml')
sites_settings_path = File.expand_path File.join(dir,'config/sites.yaml')

# start
server = RSMP::Supervisor.new({
	supervisor_settings_path: supervisor_settings_path,
	sites_settings_path: sites_settings_path
})
server.run
