port: 12111
guest:
  sxl: tlc
  type: tlc
  intervals:
    timer: 0.1
    watchdog: 0.1
  timeouts:
    watchdog: 0.2
    acknowledgement: 0.2
log:
  port: true
  site_id: 9
  component: 2
  direction: false
  level: false
  debug: true
  json: true
